name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # - name: Run build
      #   run: |
      #     npm ci
      #     npm run build --if-present
      # - name: Run tests
      #   run: npm test
      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Push commit to main
        if: ${{success()}}
        run: |
          git checkout main
          git merge dev --no-edit
          git push origin main
