name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run build
        run: |
          npm ci
          npm run build --if-present
      - name: Run tests
        run: npm test
        
  pull-to-main:
      runs-on: ubuntu-latest
      needs: build
      strategy:
        matrix:
          node-version: [18.x]
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: pull request to main
          run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            gh pr create -B main -H dev --title 'Merge dev into main' --body 'Created by Github action'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

